kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  namespace: nginx
  labels:
    app: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain #even when pvc is deleted pv is present and data is preserved (manually reviewed or reused later)
  hostPath:
    path: /mnt/data

  